/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'yasser' at '6/9/15 3:54 PM' with Gradle 2.4
 *
 * @author yasser, @date 6/9/15 3:54 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
